apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:JkI9gL+tjC7RZbf/8QcKqA==,iv:IfdJyWbU+n+DDyNPGX+L8SPaD0VMqdYboByz4YTPtZU=,tag:kabuZ86EtosLvs5gONxyew==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:2G0RXIkHTs4ltoG8,iv:Y/B7ZgLL8L8jWntvktG5ccqa2kbeUuWBhnySJhgMomA=,tag:nU12Vgz5IR2re7RcChcibw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-container-env
sops:
    age:
        - recipient: age1xeva6dxpryfrfewz6cwstd6vemrnu0yq8xu59ax9n9r2ft4nlshqvgwmdj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZWVabnNwR2NNRTJvcXpm
            UUptV1pXWUd0YkNlYUl5aWJUMEY1NmJLNUM4Ck0wNDhhNW4zRUZvZjJGME1PTHlx
            d3UrV3kxZmhlMjFoM0ZOMkc0NlNGS2MKLS0tIGJDTWRMUFlsQVBTbFY4ZVZPZE5a
            OUZkWkZ2M2RIdjlUY1E2b0hpT1M5OWMKxZeTDwZJtl5VhHKL+ckOmm6Os9j3OBVO
            7e8urq8bvDU2va5X0law/YNZGOnBg81VAioWGoKmUcnoLuwDPWSL4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T14:20:42Z"
    mac: ENC[AES256_GCM,data:NEjwtzj8U9V1b+Uv1P7aLEwxWQ7CsCym80WA7wTFdOZng+aQhtKnjGayhjO1f6iuZT3FAmuvhN0gbmkkpcrLG2XBcbigxYuR7zD4vdOk46pZDQnc+yfBDKM5labpL+uKUlJOErIpTwu2AuHN2tNw0gkYH6HqtJVnTCXlprXjRII=,iv:eoHhKPSzrDbhD5oqcFnN0RnWBb8SXXgoqSc/r/0fbGc=,tag:Gn30sjdPYAw9PtEnzGXNIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
