apiVersion: v1
data:
    password: ENC[AES256_GCM,data:MhYmf1IU/GA=,iv:ydDM9m4Jtv7cbIi15fwd75OkvHPcZESpJviQWQj5a08=,tag:g/fSSBrPDAseDP35d6Dj3Q==,type:str]
    user: ENC[AES256_GCM,data:wjKVWiNSmbY=,iv:Du2SxV9nIymzk5X5OqpaQMZtP9n3m+Ub1iMEMGv6amk=,tag:433iSr4QUWudVAVyax3Olg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1xeva6dxpryfrfewz6cwstd6vemrnu0yq8xu59ax9n9r2ft4nlshqvgwmdj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SjFwNGc5NnducTZ1R2VN
            ZExWK0FYc0VWNnV0RjdIRnJBVUcxUHRkaUNFClhJNk92M2hJbll0WC9qQm9JcS95
            ZmRMalBSa2ltQUpCZ3g2UTJITXE3RGMKLS0tIG9qWVA4ZWptdmVjaUZYWDhudlA2
            N0c4ZkVMQ3QzK0dRMHQxc0cxeUNMM3cKove3XRMyoF1VtVfcKaiXGQQfadlsmuNW
            jBvT26aJ+IHZe8P/OS7LL81DqF/GsMloEJiwbJURTPNrPPC0LPb7mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T13:24:25Z"
    mac: ENC[AES256_GCM,data:nuBRCZxA9LKAUTIjwxMAxW1ljTG5tr/Az8kn+76qWDkxRqe+nDgx+MygkaIREXdK79mU8/5GmL4c/L6LaDYchlGSoMnU41qmQvacIB3cLjjjBiuIoVMd+V34Cm220mbLp4eMEjjVv2bGR269bwZWOY/pn9f5huXzJ/dI4cVDCnc=,iv:DpwQ0pc4fDlQIMRoIELyMgpiNmt397vsn9BB7u2/Uyc=,tag:aC7l2jiNN4iDXW+kS68GwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
